# Generated by Django 6.0.5 on 2026-05-27 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_terapeuta', models.CharField(help_text='Nome exibido nos agendamentos e comissões.', max_length=150, verbose_name='Nome profissional')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, help_text='Ex: 30.00 para 30%. Usado no cálculo automático ao concluir o atendimento.', max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='O percentual não pode ser negativo.'), django.core.validators.MaxValueValidator(100, message='O percentual não pode ultrapassar 100%.')], verbose_name='Percentual de comissão (%)')),
                ('ativo', models.BooleanField(default=True, help_text='Terapeutas inativos não aparecem na lista de vínculo de agendamentos.', verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terapeuta', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema')),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
                'ordering': ['nome_terapeuta'],
            },
        ),
    ]
