# Generated by Django 6.0.5 on 2026-05-27 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0002_servico_imagem'),
        ('terapeutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_promocional', models.CharField(help_text='Código que o cliente digita. Ex: YOONA10', max_length=30, unique=True, verbose_name='Código promocional')),
                ('tipo_desconto', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor fixo (R$)')], max_length=10, verbose_name='Tipo de desconto')),
                ('valor_desconto', models.DecimalField(decimal_places=2, help_text='Para percentual: ex. 10.00 = 10%. Para fixo: ex. 20.00 = R$ 20,00.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do desconto')),
                ('status_voucher', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status')),
                ('limite_uso', models.PositiveIntegerField(help_text='Quantas vezes este voucher pode ser utilizado no total.', verbose_name='Limite de usos')),
                ('usos_realizados', models.PositiveIntegerField(default=0, help_text='Contador atualizado automaticamente a cada uso.', verbose_name='Usos realizados')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data')),
                ('horario_agendamento', models.TimeField(verbose_name='Horário')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando', max_length=12, verbose_name='Status')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, help_text='Preenchido automaticamente ao concluir o atendimento.', max_digits=10, null=True, verbose_name='Valor final (R$)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clientes.cliente', verbose_name='Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='servicos.servico', verbose_name='Serviço')),
                ('terapeuta', models.ForeignKey(blank=True, help_text='Vinculado pelo administrador após o agendamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='terapeutas.terapeuta', verbose_name='Terapeuta')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='agendamentos.voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_agendamento', 'horario_agendamento'],
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_calculado', models.DecimalField(decimal_places=2, help_text='Calculado como: valor_final × percentual_comissao.', max_digits=10, verbose_name='Valor da comissão (R$)')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comissao', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to='terapeutas.terapeuta', verbose_name='Terapeuta')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-data_registro'],
            },
        ),
    ]
