# Generated by Django 6.0.5 on 2026-05-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro')], default='pix', help_text='Forma de pagamento escolhida pelo cliente no ato do agendamento.', max_length=10, verbose_name='Método de pagamento'),
        ),
    ]
