# Generated by Django 6.0.5 on 2026-06-09 01:48

from django.db import migrations, models


def seed_domingo(apps, schema_editor):
    BloqueioAgenda = apps.get_model('agendamentos', 'BloqueioAgenda')
    BloqueioAgenda.objects.create(
        tipo='dia_semana',
        dia_semana=6,  # Domingo (Python weekday)
        motivo='Fechado aos domingos',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento_metodo_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dia_semana', 'Dia da semana (recorrente)'), ('data', 'Data específica')], max_length=10, verbose_name='Tipo')),
                ('dia_semana', models.SmallIntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia da semana')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data específica')),
                ('motivo', models.CharField(blank=True, max_length=120, verbose_name='Motivo / Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda',
                'verbose_name_plural': 'Bloqueios de Agenda',
                'ordering': ['tipo', 'dia_semana', 'data'],
            },
        ),
        migrations.RunPython(seed_domingo, migrations.RunPython.noop),
    ]
