# Generated by Django 6.0.5 on 2026-06-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_adiciona_status_em_andamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Opcional. Deixe em branco para um voucher sem prazo de expiração.', null=True, verbose_name='Data de validade'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='limite_uso',
            field=models.PositiveIntegerField(blank=True, help_text='Quantas vezes este voucher pode ser utilizado no total. Em branco ou 0 = ilimitado.', null=True, verbose_name='Limite de usos'),
        ),
    ]
