# Generated by Django 6.0.4 on 2026-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tratamento')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('duracao', models.IntegerField(help_text='Duração em minutos', verbose_name='Duração Estimada')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Base')),
                ('ativo', models.BooleanField(default=True, verbose_name='Status de Disponibilidade')),
            ],
            options={
                'verbose_name': 'Terapia/Serviço',
                'verbose_name_plural': 'Terapias e Serviços',
                'ordering': ['nome'],
            },
        ),
    ]
