# Generated by Django 6.0.4 on 2026-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Apenas imagens com resolução 16:9', null=True, upload_to='servicos/imagens/', verbose_name='Imagem do Serviço'),
        ),
    ]
