# Generated by Django 6.0.5 on 2026-05-27 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, help_text='Cosméticos, óleos essenciais, látex etc. Deixe em branco se não houver.', verbose_name='Alergias conhecidas')),
                ('sensibilidades', models.CharField(choices=[('normal', 'Normal (sem incômodos frequentes)'), ('sensivel', 'Sensível (fica irritado com facilidade)'), ('dermatite', 'Dermatite, descamação ou caspa ativa'), ('dor', 'Sinto dor ao toque ou ao prender o cabelo')], default='normal', max_length=20, verbose_name='Sensibilidade do couro cabeludo')),
                ('procedimentos_anteriores', models.TextField(blank=True, help_text='Alisamentos, descolorações, tinturas — e há quanto tempo.', verbose_name='Procedimentos químicos anteriores')),
                ('preferencias', models.TextField(blank=True, help_text='Pressão da massagem, aromas preferidos, silêncio etc.', verbose_name='Preferências de atendimento')),
                ('consentimento_lgpd', models.BooleanField(default=False, help_text='Cliente autorizou o armazenamento dos dados de saúde capilar.', verbose_name='Consentimento LGPD')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True, verbose_name='Preenchido em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
    ]
