# Generated by Django 6.0.5 on 2026-06-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='sensibilidades',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='alergias_detalhes',
            field=models.TextField(blank=True, help_text='Cosméticos, óleos essenciais, látex etc.', verbose_name='Quais alergias?'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='medicamentos_detalhes',
            field=models.TextField(blank=True, verbose_name='Quais medicamentos?'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='sensibilidade_detalhes',
            field=models.TextField(blank=True, help_text='Descreva quando/como ocorre.', verbose_name='Detalhes da sensibilidade'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tem_alergias',
            field=models.BooleanField(default=False, verbose_name='Possui alergias?'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tem_sensibilidade',
            field=models.BooleanField(default=False, verbose_name='Possui sensibilidade no couro cabeludo?'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_medicamentos',
            field=models.BooleanField(default=False, verbose_name='Usa medicamentos de uso contínuo?'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='consentimento_lgpd',
            field=models.BooleanField(default=False, verbose_name='Consentimento LGPD'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='preferencias',
            field=models.TextField(blank=True, help_text='Pressão da massagem, aromas preferidos, silêncio etc.', verbose_name='Preferências e observações adicionais'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='procedimentos_anteriores',
            field=models.TextField(blank=True, help_text='Alisamentos, descolorações, tinturas — e há quanto tempo.', verbose_name='Procedimentos químicos recentes'),
        ),
    ]
